In [1]:
import numpy as np

In [2]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
transpose_arr = np.transpose(arr)
print("Original Array: \n", arr)
print("Transposed Array: \n", transpose_arr)

Original Array: 
 [[1 2 3]
 [4 5 6]]
Transposed Array: 
 [[1 4]
 [2 5]
 [3 6]]
