In [2]:
import numpy as np

# Summing the Values in an Array

In [12]:
rng = np.random.default_rng()
L = rng.random(100)
sum(L)


array([0.168008  , 0.50289119, 0.31765942, 0.75047362, 0.77556415,
       0.87842384, 0.58656634, 0.79296479, 0.78054466, 0.94663544,
       0.24566245, 0.93884034, 0.20494375, 0.70442963, 0.81961779,
       0.45937041, 0.2955379 , 0.55060052, 0.03855055, 0.32835101,
       0.41976319, 0.59858295, 0.03232857, 0.01297816, 0.21937629,
       0.15091475, 0.61938226, 0.93711927, 0.26452819, 0.70191516,
       0.45377994, 0.52382562, 0.25372353, 0.59292786, 0.46937319,
       0.24671826, 0.39114753, 0.7279268 , 0.95206551, 0.9711507 ,
       0.67919957, 0.19364947, 0.18511035, 0.56063401, 0.89580308,
       0.12276567, 0.89122572, 0.25381757, 0.10513938, 0.93963712,
       0.75715097, 0.09164023, 0.06168636, 0.69588679, 0.52355411,
       0.74987224, 0.29636055, 0.1431635 , 0.03814579, 0.84269728,
       0.57273042, 0.7196291 , 0.21357057, 0.19654306, 0.64310454,
       0.17732896, 0.80381558, 0.46092588, 0.88502142, 0.36569897,
       0.77168179, 0.47991563, 0.65836719, 0.36311488, 0.80409

The syntax is quite similar to that of NumPy’s sum function, and the result is the same
in the simplest case:

In [4]:
np.sum(L)

52.72698595559473

However, because it executes the operation in compiled code, NumPy’s version of the
operation is computed much more quickly:

In [5]:
big_array = rng.random(1000000)
%timeit sum(big_array)


324 ms ± 43 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [6]:
%timeit np.sum(big_array)

2.57 ms ± 140 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


# Minimum and Maximum

Similarly, Python has built-in min and max functions, used to find the minimum value
and maximum value of any given array:

In [7]:
print(max(big_array))
print(min(big_array))

0.9999993001509779
1.5287986253609276e-06


NumPy’s corresponding functions have similar syntax, and again operate much more
quickly:

In [8]:
np.max(big_array), np.min(big_array)

(0.9999993001509779, 1.5287986253609276e-06)

In [9]:
%timeit np.max(big_array)

1.18 ms ± 307 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [10]:
%timeit max(big_array)

162 ms ± 10.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


For min, max, sum, and several other NumPy aggregates, a shorter syntax is to use
methods of the array object itself:

In [11]:
big_array.min(), big_array.max(), big_array.sum()

(1.5287986253609276e-06, 0.9999993001509779, 500253.7344227678)

# Multidimensional Aggregates

In [13]:
M = rng.integers(0, 10, (3, 4))
print(M)

[[6 6 0 1]
 [8 0 5 7]
 [6 5 4 7]]


In [14]:
M.sum()

55

we can find the minimum value within each
column by specifying axis=0:

In [15]:
M.min(axis = 0)

array([6, 0, 0, 1], dtype=int64)

Similarly, we can find the maximum value within each row:

In [22]:
M.max(axis = 1)

array([6, 8, 7], dtype=int64)