In [1]:
import numpy as np

Recall that for arrays of the same size, binary operations are performed on an
element-by-element basis:

In [3]:
a = np.array([0, 1, 2])
b = np.array([5, 5, 5])
a + b

array([5, 6, 7])

we can just as easily add a scalar (think of it as a zerodimensional
array) to an array

In [5]:
a + 5
# We can think of this as an operation that stretches or duplicates the value 5 into the 
# array [5, 5, 5], and adds the results

array([5, 6, 7])

We can similarly extend this idea to arrays of higher dimension. Observe the result
when we add a one-dimensional array to a two-dimensional array:

In [7]:
M = np.ones([3, 3])
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
M + a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

While these examples are relatively easy to understand, more complicated cases can
involve broadcasting of both arrays. Consider the following example:

In [10]:
c = np.arange(3)
d = np.arange(3)[:, np.newaxis]
print(f"{c}\n{d}")

[0 1 2]
[[0]
 [1]
 [2]]


In [11]:
c + d

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])