In [1]:
import numpy as np # type: ignore

# Fast Sorting in NumPy: np.sort and np.argsort

In [2]:
x = np.array([2, 1, 4, 3, 5])
np.sort(x)

array([1, 2, 3, 4, 5])

A related function is argsort, which instead returns the indices of the sorted elements:

In [3]:
i = np.argsort(x)
print(i)

[1 0 3 2 4]


The first element of this result gives the index of the smallest element, the second
value gives the index of the second smallest, and so on. These indices can then be
used (via fancy indexing) to construct the sorted array if desired:

In [4]:
x[i]

array([1, 2, 3, 4, 5])