In [2]:
import numpy as np # type: ignore

Sometimes we’re not interested in sorting the entire array, but simply want to find the
k smallest values in the array. NumPy enables this with the np.partition function.
np.partition takes an array and a number k; the result is a new array with the smallest
k values to the left of the partition and the remaining values to the right:

simple english: returns values less than number k on the left and the remaining on the right.

In [6]:
x = np.array([7, 2, 3, 1, 6, 5, 4])
np.partition(x, 3)

array([2, 1, 3, 4, 6, 5, 7])

In [9]:
rng = np.random.default_rng(seed=42)
y = rng.integers(0, 10, (4, 6))
print(y)

[[0 7 6 4 4 8]
 [0 6 2 0 5 9]
 [7 7 7 7 5 1]
 [8 4 5 3 1 9]]


Similarly to sorting, we can partition along an arbitrary axis of a multidimensional
array:

In [22]:
print("sort along each row\n", np.partition(y, 2, axis=1))
print()
print("sort along each column\n", np.partition(y, 2, axis=0))

sort along each row
 [[0 4 4 7 6 8]
 [0 0 2 6 5 9]
 [1 5 7 7 7 7]
 [1 3 4 5 8 9]]

sort along each column
 [[0 4 2 0 1 1]
 [0 6 5 3 4 8]
 [7 7 6 4 5 9]
 [8 7 7 7 5 9]]


Finally, just as there is an np.argsort function that computes indices of the sort,
there is an np.argpartition function that computes indices of the partition. We’ll see
both of these in action in the following section.

In [23]:
print("sort along each row\n", np.argpartition(y, 2, axis=1))
print()
print("sort along each column\n", np.argpartition(y, 2, axis=0))

sort along each row
 [[0 3 4 1 2 5]
 [0 3 2 1 4 5]
 [5 4 2 3 1 0]
 [4 3 1 2 0 5]]

sort along each column
 [[0 3 1 1 3 2]
 [1 1 3 3 0 0]
 [2 2 0 0 2 1]
 [3 0 2 2 1 3]]
