# Creating Array from Python Lists

In [5]:
import numpy as np;

In [6]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [7]:
# upcast
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

Explicitly set data type

In [9]:
np.array([1, 2, 3, 4, 5], dtype=np.float32)

array([1., 2., 3., 4., 5.], dtype=float32)

initializing a multidimensional array using list of lists.


In [10]:
# nested lists result in multidimensional arrays
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])