In [1]:
import numpy as np

In [6]:
# create a length-10 integer array filled with 0s.
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
# create a 3x5 floating poing array filled with 1s.
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
# create a 3x5 array filled with 3.14
np.full([3, 5], 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [14]:
# create an array filled with a linear sequence 
# starting at 0, ending at 20, stepping by 2
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
# create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [16]:
# <!-- create a 3x3 array of uniformly distributed pseudorandom values betwwen 0 and 1 -->
np.random.random((3, 3))

array([[0.12876054, 0.96156288, 0.73582444],
       [0.44707265, 0.16839512, 0.50467065],
       [0.56514905, 0.87280018, 0.69139936]])

In [17]:
# create a 3x3 array of normally distributed pseudorandom values with mean 0 and std 1
np.random.normal(0, 1, (3, 3))

array([[ 0.42953309, -0.56142932, -1.66409775],
       [-0.78732492,  0.40683957,  0.77069057],
       [ 0.10575295,  0.73575464, -0.77131359]])

In [27]:
# create a 3x3 array of pseudorandom integers in rhe interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[3, 1, 6],
       [0, 1, 4],
       [9, 6, 7]])

In [19]:
# create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
# create an uninitialized array of three inetgers
np.empty(3)

array([1., 1., 1.])