In [1]:
import numpy as np

In [24]:
rng = np.random.default_rng(seed=1701) # seed for reproducibility

x1 = rng.integers(10, size=6) # 1D array
x2 = rng.integers(10, size=(3, 4)) # 2D array
x3 = rng.integers(10, size=(3, 4, 5)) # 3D array


In [25]:
print("X1: ", x1)
print("X2: ", x2)
print("X3: ", x3)

X1:  [9 4 0 3 8 6]
X2:  [[3 1 3 7]
 [4 0 2 3]
 [0 0 6 9]]
X3:  [[[4 3 5 5 0]
  [8 3 5 2 2]
  [1 8 8 5 3]
  [0 0 8 5 8]]

 [[5 1 6 2 3]
  [1 2 5 6 2]
  [5 2 7 9 3]
  [5 6 0 2 0]]

 [[2 9 4 3 9]
  [9 2 2 4 0]
  [0 3 0 0 2]
  [3 2 7 4 7]]]


In [26]:
print(x3.ndim)
print(x3.size)
print(x3.shape)
print(x2.ndim)

3
60
(3, 4, 5)
2
