In [1]:
import numpy as np

In [2]:
rng = np.random.default_rng(seed=1701) # seed for reproducibility

x1 = rng.integers(10, size=6) # 1D array
x2 = rng.integers(10, size=(3, 4)) # 2D array
x3 = rng.integers(10, size=(3, 4, 5)) # 3D array

In [4]:
x1[0]

9

In [5]:
x1[4]

8

# To index from the end of the array, you can use negative indices:

In [6]:
x1[-1]

6

In [7]:
x1[-2]

8

In multidimensional array, items can be accessed using a comma-seperated(row, column) tuple:

In [8]:
x2

array([[3, 1, 3, 7],
       [4, 0, 2, 3],
       [0, 0, 6, 9]], dtype=int64)

In [9]:
x2[0, 0]

3

In [10]:
x2[2, 0]

0

In [11]:
x2[2, -1]

9

Values can also be modified using any of the preceding index notation:

In [13]:
x2[0, 0] = 12
x2

array([[12,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]], dtype=int64)

If you attempt to insert a floating-point value in an integer array, the value will be silently truncated.


In [14]:
x1[0] = 3.14159 # this will be truncated!
x1

array([3, 4, 0, 3, 8, 6], dtype=int64)