In [1]:
import numpy as np

In [2]:
rng = np.random.default_rng(seed=1701) # seed for reproducibility

x1 = rng.integers(10, size=6) # 1D array
x2 = rng.integers(10, size=(3, 4)) # 2D array
x3 = rng.integers(10, size=(3, 4, 5)) # 3D array

One-Dimensional Subarrays

In [5]:
x1[0] = 3.14159
x1

array([3, 4, 0, 3, 8, 6], dtype=int64)

In [10]:
print("First three elements: ", x1[:3])
print("Elements after index3: ", x1[3:])
print("Middle subarray: ", x1[1:4])
print("Every second element: ", x1[::2])
print("Every second element, starting at index 1: ", x1[1::2])

First three elements:  [3 4 0]
Elements after index3:  [3 8 6]
Middle subarray:  [4 0 3]
Every second element:  [3 0 8]
Every second element, starting at index 1:  [4 3 6]


A potentially confusing case is when the step value is negative. In this case, the
defaults for start and stop are swapped. This becomes a convenient way to reverse
an array:

In [18]:
x1[::-1]

array([6, 8, 3, 0, 4, 3], dtype=int64)

In [19]:
x1[4::-2] # every second element form index 4, reversed.

array([8, 0, 3], dtype=int64)

Multidimensional Subarrays

In [21]:
x2

array([[3, 1, 3, 7],
       [4, 0, 2, 3],
       [0, 0, 6, 9]], dtype=int64)

In [20]:
x2[:2, :3] # first two rows and three columns

array([[3, 1, 3],
       [4, 0, 2]], dtype=int64)

In [24]:
# Three rows, every second columns
x2[:3, ::2]

array([[3, 3],
       [4, 2],
       [0, 6]], dtype=int64)

In [26]:
# All rows and columns reversed.
x2[::-1, ::-1]

array([[9, 6, 0, 0],
       [3, 2, 0, 4],
       [7, 3, 1, 3]], dtype=int64)

One commonly needed routine is accessing single rows or columns of an array. This
can be done by combining indexing and slicing, using an empty slice marked by a
single colon (:)

In [28]:
x2[:, 0] # first column of x2

array([3, 4, 0], dtype=int64)

In [29]:
# first row of x2
x2[0, :]

array([3, 1, 3, 7], dtype=int64)

In the case of row access, the empty slice can be omitted for a more compact syntax:

In [30]:
x2[0] # this is equivalent to x2[0, :]

array([3, 1, 3, 7], dtype=int64)