In [1]:
import numpy as np

In [2]:
rng = np.random.default_rng(seed=1701) # seed for reproducibility

x1 = rng.integers(10, size=6) # 1D array
x2 = rng.integers(10, size=(3, 4)) # 2D array
x3 = rng.integers(10, size=(3, 4, 5)) # 3D array

Unlike Python list slices, NumPy array slices are returned as views rather than copies
of the array data

In [3]:
x2

array([[3, 1, 3, 7],
       [4, 0, 2, 3],
       [0, 0, 6, 9]], dtype=int64)

Let’s extract a 2 × 2 subarray from this:

In [5]:
x2_sub = x2[:2, :2]
x2

array([[3, 1, 3, 7],
       [4, 0, 2, 3],
       [0, 0, 6, 9]], dtype=int64)

Now if we modify this subarray, we’ll see that the original array is changed! Observe:

In [6]:
x2_sub[0, 0] = 99
x2_sub

array([[99,  1],
       [ 4,  0]], dtype=int64)

In [7]:
x2

array([[99,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]], dtype=int64)

# Creating Copies of Arrays


In [8]:
x2_sub_copy = x2_sub.copy()
x2_sub_copy

array([[99,  1],
       [ 4,  0]], dtype=int64)

In [9]:
x2_sub_copy[0, 0] = 42
x2_sub_copy

array([[42,  1],
       [ 4,  0]], dtype=int64)

In [10]:
x2

array([[99,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]], dtype=int64)