In [1]:
import numpy as np

In [3]:
# Numbers from 1-9 in a 3x3 grid
grid = np.arange(1, 10).reshape(3, 3)
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

A common reshaping operation is converting a one-dimensional array into a twodimensional
row or column matrix:

In [8]:
# Row vector via reshape.
x = np.array([1, 2, 3])
x.reshape(1, 3)

array([[1, 2, 3]])

In [10]:
# Column vector via reshape.
x.reshape([3, 1])

array([[1],
       [2],
       [3]])

A convenient shorthand for this is to use np.newaxis in the slicing syntax

In [12]:
# Row vector via newaxixs
x[np.newaxis, :]

array([[1, 2, 3]])

In [13]:
# Column vector via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])