In [2]:
import numpy as np;

# Concatenation of Arrays
Concatenation, or joining of two arrays in NumPy, is primarily accomplished using
the routines np.concatenate, np.vstack, and np.hstack. np.concatenate takes a
tuple or list of arrays as its first argument, as you can see here:

In [25]:
x = np.array([1, 4, 3])
y = np.array([3, 2, 1])
x_y = np.concatenate([x, y])
x_y

array([1, 4, 3, 3, 2, 1])

You can also concatenate more than two arrays at once:

In [26]:
z = np.array([99, 99, 99])
x_y_z = np.concatenate([x, y, z])
x_y_z

array([ 1,  4,  3,  3,  2,  1, 99, 99, 99])

And it can be used for two-dimensional arrays:

In [27]:
_2x2 = x_y.reshape([2, 3])
_2x2

array([[1, 4, 3],
       [3, 2, 1]])

In [28]:
# Concatenate along the first axis
np.concatenate([_2x2, _2x2])

array([[1, 4, 3],
       [3, 2, 1],
       [1, 4, 3],
       [3, 2, 1]])

In [29]:
# # Concatenate along the second axis (zero-indexed)
np.concatenate([_2x2, _2x2], axis = 1)

array([[1, 4, 3, 1, 4, 3],
       [3, 2, 1, 3, 2, 1]])

For working with arrays of mixed dimensions, it can be clearer to use the np.vstack
(vertical stack) and np.hstack (horizontal stack) functions

In [30]:
# Vertically stack the array.
np.vstack([x, _2x2])

array([[1, 4, 3],
       [1, 4, 3],
       [3, 2, 1]])

In [32]:
# Horizontally stsck the arrays.
y = np.array([[99], [99]])
np.hstack([_2x2, y])

array([[ 1,  4,  3, 99],
       [ 3,  2,  1, 99]])