In [1]:
import numpy as np

# Splitting of Arrays
The opposite of concatenation is splitting, which is implemented by the functions
np.split, np.hsplit, and np.vsplit. For each of these, we can pass a list of indices
giving the split points:

In [2]:
x = np.array([1, 2, 3, 99, 99, 3, 2, 1])

In [8]:
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


Notice that N split points leads to N + 1 subarrays. The related functions np.hsplit
and np.vsplit are similar:

In [9]:
grid = np.arange(16).reshape([4, 4])
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [16]:
# Vsplit arrays.
upper, lower = np.vsplit(grid, 2)
print("Upper: ", upper)
print("Lower: ", lower)

Upper:  [[0 1 2 3]
 [4 5 6 7]]
Lower:  [[ 8  9 10 11]
 [12 13 14 15]]


In [24]:
# Horizontally splitting arrays
left, right = np.hsplit(grid, 2)
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [47]:
arr = np.array([1, 2, 3, 4, 5, 6])
split_arrays = np.split(arr, [2, 4])
    
def func():
    for j in range(len(split_arrays)):
        print(j)
        
f = func() 

for i in split_arrays: 
    print(f'Array {f}: {i}')

0
1
2
Array None: [1 2]
Array None: [3 4]
Array None: [5 6]
