In [1]:
import numpy as np

In [15]:
x = np.arange(16).reshape(4, 4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [16]:
x[:2, :3] # first two rows and first three columns

array([[0, 1, 2],
       [4, 5, 6]])

In [20]:
x[:3, ::2] # Three rows, every second column

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [21]:
x[::-1, ::-1] # All rows and columns reversed

array([[15, 14, 13, 12],
       [11, 10,  9,  8],
       [ 7,  6,  5,  4],
       [ 3,  2,  1,  0]])

In [22]:
x[:, 0] # first columns of x

array([ 0,  4,  8, 12])

In [23]:
x[0, :] # first row of x

array([0, 1, 2, 3])