In [1]:
import numpy as np

In [6]:
grid = np.arange(1, 10).reshape(3, 3)
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
# row vector matrix
grid.reshape(1, 9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [8]:
# column vector matrix
grid.reshape(9, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

A shorthand for this is to use np.newaxis in the slicing syntax

Row vector matrix

In [11]:
x = grid.copy()

In [13]:
x[np.newaxis, :]

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])