In [1]:
import numpy as np

In [16]:
x = np.array(
    [1, 2, 3]
)

In [17]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [18]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [20]:
x.reshape(3, 1)

array([[1],
       [2],
       [3]])