In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

In [6]:
# concatenate array
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [11]:
# concat more than two arrays at once
z = np.array([99, 99, 99])
np.concatenate([x, y, z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [12]:
# concatenate 2D array
grid = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
gride = np.array([
    [1, 2, 4],
    [4, 5, 6]
])

# concatenate along the first axis
np.concatenate([grid, gride])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 4],
       [4, 5, 6]])

In [13]:
# concatenate along the second axis
np.concatenate([grid, gride], axis=1)

array([[1, 2, 3, 1, 2, 4],
       [4, 5, 6, 4, 5, 6]])